# Generated by Django 5.2.1 on 2025-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
