# Generated by Django 5.2.1 on 2025-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmodel_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='contentUrl',
            field=models.FileField(upload_to='media/posts/'),
        ),
    ]
