# Generated by Django 5.2.1 on 2025-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postmodel_contenturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='contentUrl',
            field=models.FileField(upload_to=''),
        ),
    ]
