# Generated by Django 5.2.1 on 2025-06-12 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 18, 57, 40, 926895)),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 18, 57, 40, 926895)),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 18, 57, 40, 926895)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 18, 57, 40, 926895)),
        ),
    ]
