# Generated by Django 5.2.1 on 2025-06-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_clone', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='View',
        ),
    ]
