# Generated by Django 5.2.1 on 2025-06-17 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_clone', '0003_alter_comment_created_at_alter_follow_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 19, 3, 31, 181780)),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 19, 3, 31, 181780)),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 19, 3, 31, 180780)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 19, 3, 31, 179768)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
